-- PropertyFlow Professional — demo seed
-- Bootstrap the database with the 10 demo properties shipped in src/data/properties.json.
-- Run AFTER supabase/schema.sql.

INSERT INTO public.properties (title_en, title_pt, city_en, city_pt, country_en, country_pt, category, type_en, type_pt, beds, baths, area_m2, price_eur, currency, status, image, summary_en, summary_pt, tags_en, tags_pt) VALUES
  ('Riverside Penthouse Loft', 'Loft Penthouse à Beira-Rio', 'Lisbon', 'Lisboa', 'Portugal', 'Portugal', 'luxury', 'Apartment', 'Apartamento', 3, 2, 156, 1290000, 'EUR', 'for-sale', '/images/property-01.svg', 'Top-floor loft with panoramic Tagus river views, double-height ceilings and a private 28 m² terrace.', 'Loft de cobertura com vista panorâmica do Tejo, pé-direito duplo e terraço privativo de 28 m².', ARRAY['riverside','penthouse','renovated','parking'], ARRAY['beira-rio','penthouse','reformado','estacionamento']),
  ('Tiled Townhouse · Foz', 'Casa de Azulejos · Foz', 'Porto', 'Porto', 'Portugal', 'Portugal', 'premium', 'Townhouse', 'Casa Geminada', 4, 3, 210, 875000, 'EUR', 'for-sale', '/images/property-02.svg', 'Restored 1920s townhouse in Foz with original azulejo facade, three floors and a private south-facing garden.', 'Casa restaurada dos anos 20 na Foz com fachada de azulejos original, três andares e jardim privado virado a sul.', ARRAY['historic','tiles','garden','near-beach'], ARRAY['histórico','azulejos','jardim','perto-da-praia']),
  ('Cliffside Villa · Lagos', 'Villa na Falésia · Lagos', 'Lagos', 'Lagos', 'Portugal', 'Portugal', 'luxury', 'Villa', 'Villa', 5, 4, 340, 2450000, 'EUR', 'for-sale', '/images/property-03.svg', 'Modern five-bedroom villa carved into the Atlantic cliffs with infinity pool and direct sea-cave access.', 'Villa moderna de cinco quartos esculpida na falésia atlântica com piscina infinita e acesso direto às grutas do mar.', ARRAY['ocean-view','pool','cliffside','luxury'], ARRAY['vista-mar','piscina','falésia','luxo']),
  ('Bairro Alto Studio', 'Estúdio no Bairro Alto', 'Lisbon', 'Lisboa', 'Portugal', 'Portugal', 'rental', 'Studio', 'Estúdio', 0, 1, 38, 1450, 'EUR', 'for-rent', '/images/property-04.svg', 'Compact furnished studio in the heart of Bairro Alto, fully equipped, monthly rental.', 'Estúdio mobiliado no coração do Bairro Alto, totalmente equipado, aluguel mensal.', ARRAY['furnished','central','nightlife','monthly'], ARRAY['mobiliado','central','vida-noturna','mensal']),
  ('Family House · Cascais Hills', 'Casa de Família · Serra de Cascais', 'Cascais', 'Cascais', 'Portugal', 'Portugal', 'premium', 'House', 'Casa', 4, 3, 245, 1180000, 'EUR', 'for-sale', '/images/property-05.svg', 'South-facing four-bedroom house on the green hills above Cascais, walking distance to Guincho beach.', 'Casa de quatro quartos virada a sul nas colinas verdes de Cascais, a poucos minutos da praia do Guincho.', ARRAY['garden','garage','near-beach','family'], ARRAY['jardim','garagem','perto-da-praia','família']),
  ('Marquês Office Floor', 'Andar de Escritórios · Marquês', 'Lisbon', 'Lisboa', 'Portugal', 'Portugal', 'commercial', 'Office', 'Escritório', 0, 2, 320, 4800, 'EUR', 'for-rent', '/images/property-06.svg', 'Open-plan office floor with 18 workstations, three meeting rooms and a south-facing terrace at Marquês.', 'Andar open-plan com 18 postos, três salas de reunião e terraço virado a sul, no Marquês.', ARRAY['central','fitted','metro','open-plan'], ARRAY['central','equipado','metro','open-plan']),
  ('Restored Alentejo Farmhouse', 'Monte Alentejano Restaurado', 'Évora', 'Évora', 'Portugal', 'Portugal', 'premium', 'Farmhouse', 'Monte', 6, 5, 480, 1620000, 'EUR', 'for-sale', '/images/property-07.svg', 'Working olive-grove farmhouse on 3.4 hectares with main house, guest cottage, pool and tasting room.', 'Monte com olival ativo em 3,4 hectares, casa principal, casa de hóspedes, piscina e sala de provas.', ARRAY['acreage','olive-grove','pool','guesthouse'], ARRAY['terreno','olival','piscina','casa-hóspedes']),
  ('Funchal Sea-View Apartment', 'Apartamento Vista-Mar · Funchal', 'Funchal', 'Funchal', 'Portugal', 'Portugal', 'rental', 'Apartment', 'Apartamento', 2, 2, 88, 2300, 'EUR', 'for-rent', '/images/property-08.svg', 'Two-bedroom apartment with wraparound balcony and full Atlantic view, available monthly.', 'Apartamento de dois quartos com varanda contínua e vista total do Atlântico, disponível mensalmente.', ARRAY['sea-view','balcony','monthly','tourist-rental'], ARRAY['vista-mar','varanda','mensal','alojamento']),
  ('Marvila Riverfront · New Build', 'Marvila Frente-Rio · Novo', 'Lisbon', 'Lisboa', 'Portugal', 'Portugal', 'premium', 'Apartment', 'Apartamento', 3, 2, 124, 940000, 'EUR', 'for-sale', '/images/property-09.svg', 'Brand-new three-bedroom apartment in the Marvila riverfront development with private garage and 10-year structural warranty.', 'Apartamento novo de três quartos no empreendimento ribeirinho de Marvila, com garagem privada e garantia estrutural de 10 anos.', ARRAY['new-build','riverside','warranty','garage'], ARRAY['novo','frente-rio','garantia','garagem']),
  ('Sintra Forest Cottage', 'Casa de Mata · Sintra', 'Sintra', 'Sintra', 'Portugal', 'Portugal', 'luxury', 'Cottage', 'Casa de Campo', 3, 2, 175, 1095000, 'EUR', 'for-sale', '/images/property-10.svg', 'Renovated stone cottage at the edge of Sintra forest, exposed beams, two fireplaces, walking distance to the Pena Park.', 'Casa de pedra reformada à beira da mata de Sintra, vigas à vista, duas lareiras, a poucos minutos do Parque da Pena.', ARRAY['forest','stone','renovated','fireplace'], ARRAY['mata','pedra','reformado','lareira'])
ON CONFLICT DO NOTHING;
